<?php
require_once "ConexionGiro.php";

class ConsultasGiroModel{

	public static function usuarios($tabla){
		$stmt = Conexion::conectar()->prepare("SELECT CLAVE,NOMBREN,NOMBREP,NOMBREM FROM $tabla");
		$stmt -> execute();
        return $stmt -> fetchAll();
        $stmt -> close();	
	}

	public static function obtenerRegistro($clave,$tabla){
		//$ultimo=" AND FECHA_SALIDA = '2099-12-31 00:00:00.000'" ;
        $stmt = ConexionGiro::conectar()->prepare("SELECT NOMBRE_RP FROM $tabla WHERE CLAVE = :clave ORDER BY FECHA_SALIDA DESC");
        $stmt->bindParam(":clave",$clave, PDO::PARAM_STR);	
        $stmt -> execute();
        return $stmt -> fetch()[0];
		$stmt -> close();	
    } 
    
	public static function giro_empleados_vigentes(){
		$stmt = ConexionGiro::conectar()->prepare("
		SELECT 
		CLAVE = RTRIM(T1.CLAVE)
		,NOMBRE =  RTRIM(RTRIM(T1.NOMBREP) + ' ' + RTRIM(T1.NOMBREM) + ' ' + RTRIM(T1.NOMBREN))
		,T1.RFC
		,CURP = RTRIM(T1.CURP)
		,T1.AFILIACION
		,T1.INGRESO
		,CLAVE_SUCURSAL = (SELECT TOP 1 RTRIM(CATALOGO) FROM SUPERVISOR_GIRO.EMPSUC WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC)
		,NOMBRE_SUCURSAL = (SELECT RTRIM(NOMBRE) FROM SUPERVISOR_GIRO.SUCURSAL WHERE CLAVE = (SELECT TOP 1 CATALOGO FROM SUPERVISOR_GIRO.EMPSUC WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC))
		,CLAVE_NOMINA = (SELECT TOP 1 CATALOGO FROM SUPERVISOR_GIRO.EMPTIPONOM WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC)
		,NOMBRE_NOMINA = SUBSTRING((SELECT DESCRIPCION FROM SUPERVISOR_GIRO.TIPONOM WHERE CLAVE = (SELECT TOP 1 CATALOGO FROM SUPERVISOR_GIRO.EMPTIPONOM WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC)),6,50)
		,CLAVE_DEPTO = (SELECT TOP 1 RTRIM(CATALOGO) FROM SUPERVISOR_GIRO.EMPDEP WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC)
		,NOMBRE_DEPTO = (SELECT RTRIM(DESCRIPCION) FROM SUPERVISOR_GIRO.DEPTO WHERE CLAVE = (SELECT TOP 1 CATALOGO FROM SUPERVISOR_GIRO.EMPDEP WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC))
		,CLAVE_PUESTO = (SELECT TOP 1 RTRIM(CATALOGO) FROM SUPERVISOR_GIRO.EMPPUES WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC)
		,NOMBRE_PUESTO = (SELECT RTRIM(DESCRIPCION) FROM SUPERVISOR_GIRO.PUESTO WHERE CLAVE = (SELECT TOP 1 CATALOGO FROM SUPERVISOR_GIRO.EMPPUES WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC))
		,S_DIARIO = (SELECT TOP 1 SDO1 FROM SUPERVISOR_GIRO.EMPSDO WHERE CLAVE = T1.CLAVE AND TIPO <> 'B' ORDER BY FECHA_SALIDA DESC)
		,S_INTEGRADO = (SELECT TOP 1 SDO3 FROM SUPERVISOR_GIRO.EMPSDO WHERE CLAVE = T1.CLAVE AND TIPO <> 'B' ORDER BY FECHA_SALIDA DESC)
		,T1.CREDITO_INFONAVIT
		,T1.INICIO_DESCUENTO_INF
		,TIPO_DESCUENTO = (CASE WHEN T1.TIPO_DESCUENTO = '1' THEN 'PORCENTAJE' ELSE (CASE WHEN T1.TIPO_DESCUENTO = '2' THEN 'MONTO' ELSE (CASE WHEN T1.TIPO_DESCUENTO = '3' THEN 'SMGDF' END) END)END)
		,T1.VALOR_DESCUENTO
		,CLAVE_TURNO = T1.TURNO
		,DESCRIPCION_TURNO = (SELECT RTRIM(DESCRIPCION) FROM SUPERVISOR_GIRO.TURNO1 WHERE CLAVE = T1.TURNO)
		,ESQUEMA = (CASE WHEN T2.SYS = 'TRUE' THEN 'SYS' ELSE (CASE WHEN T2.MIXTO = 'TRUE' THEN 'MIXTO' ELSE (CASE WHEN T2.ASIMILADO = 'TRUE' THEN 'ASIMILADO' ELSE 'EMPLEADO SIN ESQUEMA' END) END) END)
		,CLAVE_REGIMEN =T2.REGIMEN
		,DESCRIPCION_REGIMEN = RTRIM(CASE WHEN T2.REGIMEN = '99' THEN 'OTRO REGIMEN' ELSE (SELECT DESCRIPCION FROM SUPERVISOR_GIRO._REGIMEN WHERE CLAVE = RIGHT(T2.REGIMEN,1)) END)
		,CLAVE_TIPO_CONTRATO = T2.TIPO_CONTRATO
		,DESCRIPCION_TIPO_CONTRATO = (SELECT RTRIM(SUPERVISOR_GIRO._TipoContratoCFDI.DESCRIPCION) FROM SUPERVISOR_GIRO._TipoContratoCFDI WHERE SUPERVISOR_GIRO._TipoContratoCFDI.CLAVE = T2.TIPO_CONTRATO)
		,FECHA_BAJA = (CASE WHEN (SELECT TOP 1 TIPO FROM SUPERVISOR_GIRO.EMPSDO WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC) = 'B' THEN (SELECT TOP 1 FECHA FROM SUPERVISOR_GIRO.EMPSDO WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC) ELSE NULL END)
		,PAGADORA_SYS = (SELECT TOP 1 RTRIM(PAGADORA_SYS) FROM SUPERVISOR_GIRO.EMP_PATRONALES WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC)
		,NOMBRE_RP = (SELECT RTRIM(NOMBRE) FROM SUPERVISOR_GIRO.PATRONAL WHERE CLAVE = (SELECT TOP 1 PAGADORA_SYS FROM SUPERVISOR_GIRO.EMP_PATRONALES WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC))
		,REG_PATRONAL = (SELECT REGISTRO_PATRONAL FROM SUPERVISOR_GIRO.PATRONAL WHERE CLAVE = (SELECT TOP 1 PAGADORA_SYS FROM SUPERVISOR_GIRO.EMP_PATRONALES WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC))
		,PAGADORA_IAS = (SELECT TOP 1 RTRIM(PAGADORA_IAS) FROM SUPERVISOR_GIRO.EMP_PATRONALES WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC)
		,NOMBRE_PAGADORA = (SELECT RTRIM(NOMBRE) FROM SUPERVISOR_GIRO.PATRONAL WHERE CLAVE = (SELECT TOP 1 PAGADORA_IAS FROM SUPERVISOR_GIRO.EMP_PATRONALES WHERE CLAVE = T1.CLAVE ORDER BY FECHA_SALIDA DESC)) FROM SUPERVISOR_GIRO.EMPPRIN T1 INNER JOIN SUPERVISOR_GIRO.EMPEXT T2 ON T1.CLAVE = T2.CLAVE
		");
		/*
SELECT   T1.CLAVE
		,T1.NOMBREP
		,T1.NOMBREM
		,T1.NOMBREN
		,T1.RFC
		,T1.CURP
		,T1.AFILIACION
		,T1.INGRESO
		,CLAVE_SUCURSAL = T2.CATALOGO
		,NOMBRE_SUCURSAL = (SELECT [ASE19].[Supervisor_giro].[SUCURSAL].[NOMBRE] FROM [ASE19].[Supervisor_giro].[SUCURSAL] WHERE [ASE19].[Supervisor_giro].[SUCURSAL].[CLAVE] = T2.CATALOGO)
		,CLAVE_NOMINA = T1.TIPO_NOM
		,NOMBRE_NOMINA = SUBSTRING((SELECT [ASE19].[Supervisor_giro].[Tiponom].[DESCRIPCION] FROM [ASE19].[Supervisor_giro].[Tiponom] WHERE [ASE19].[Supervisor_giro].[Tiponom].[CLAVE] = T1.TIPO_NOM),6,50)
		,CLAVE_DEPTO = T3.CATALOGO
		,NOMBRE_DEPTO = (SELECT [ASE19].[Supervisor_giro].[DEPTO].DESCRIPCION FROM [ASE19].[Supervisor_giro].[DEPTO] WHERE[ASE19].[Supervisor_giro].[DEPTO].CLAVE = T3.CATALOGO)
		,CLAVE_PUESTO = T4.CATALOGO
		,NOMBRE_PUESTO = (SELECT [ASE19].[Supervisor_giro].[Puesto].DESCRIPCION FROM [ASE19].[Supervisor_giro].[Puesto] WHERE [ASE19].[Supervisor_giro].[Puesto].CLAVE = T4.CATALOGO)
			,S_DIARIO = T5.SDO1
			,S_INTEGRADO = T5.SDO3
			,CLAVE_TURNO = T1.TURNO
	
			,ESQUEMA = (CASE WHEN T6.SYS = 'TRUE' THEN 'SYS' ELSE (CASE WHEN T6.MIXTO = 'TRUE' THEN 'MIXTO' ELSE (CASE WHEN T6.ASIMILADO = 'TRUE' THEN 'ASIMILADO' ELSE 'EMPLEADO SIN ESQUEMA' END) END) END)
			,CLAVE_REGIMEN = T6.REGIMEN
			,DESCRIPCION_REGIMEN = (SELECT [ASE19].[Supervisor_giro].[_TipoRegimenCFDI].DESCRIPCION FROM [ASE19].[Supervisor_giro].[_TipoRegimenCFDI] WHERE [ASE19].[Supervisor_giro].[_TipoRegimenCFDI].CLAVE = T6.REGIMEN)
			,CLAVE_TIPO_CONTRATO = T6.TIPO_CONTRATO
			,DESCRIPCION_TIPO_CONTRATO = (SELECT [ASE19].[Supervisor_giro].[_TipoContratoCFDI].DESCRIPCION FROM [ASE19].[Supervisor_giro].[_TipoContratoCFDI] WHERE [ASE19].[Supervisor_giro].[_TipoContratoCFDI].CLAVE = T6.TIPO_CONTRATO)
			,FECHA_BAJA = (CASE WHEN T5.TIPO = 'B' THEN T5.FECHA ELSE NULL END)
			,T7.PAGADORA_SYS
			,NOMBRE_RP = (SELECT [ASE19].[Supervisor_giro].[PATRONAL].NOMBRE FROM [ASE19].[Supervisor_giro].[PATRONAL] WHERE [ASE19].[Supervisor_giro].[PATRONAL].CLAVE = T7.PAGADORA_SYS)
			,REG_PATRONAL = (SELECT [ASE19].[Supervisor_giro].[PATRONAL].REGISTRO_PATRONAL FROM [ASE19].[Supervisor_giro].[PATRONAL] WHERE [ASE19].[Supervisor_giro].[PATRONAL].CLAVE = T7.PAGADORA_SYS)
			,T7.PAGADORA_IAS
			,NOMBRE_PAGADORA = (SELECT [ASE19].[Supervisor_giro].[PATRONAL].NOMBRE FROM [ASE19].[Supervisor_giro].[PATRONAL] WHERE [ASE19].[Supervisor_giro].[PATRONAL].CLAVE = T7.PAGADORA_IAS)

		FROM [ASE19].[Supervisor_giro].[Empprin] T1
		INNER JOIN [ASE19].[Supervisor_giro].[Empsuc] T2 ON T1.CLAVE = T2.CLAVE
		INNER JOIN [ASE19].[Supervisor_giro].[Empdep] T3 ON T1.CLAVE = T3.CLAVE
		INNER JOIN [ASE19].[Supervisor_giro].[Emppues] T4 ON T1.CLAVE = T4.CLAVE
		INNER JOIN [ASE19].[Supervisor_giro].[Empsdo] T5 ON T1.CLAVE = T5.CLAVE
		INNER JOIN [ASE19].[Supervisor_giro].[EMPEXT] T6 ON T1.CLAVE = T6.CLAVE
		INNER JOIN [ASE19].[Supervisor_giro].[EMP_PATRONALES] T7 ON T1.CLAVE = T7.CLAVE
		
		WHERE	T2.FECHA_SALIDA > GETDATE()
			AND T3.FECHA_SALIDA > GETDATE()
			AND T4.FECHA_SALIDA > GETDATE()
			AND T5.FECHA_SALIDA > GETDATE() 
			AND T7.FECHA_SALIDA > GETDATE()
		ORDER BY T1.CLAVE*/

        $stmt -> execute();
        return $stmt -> fetchAll();
        $stmt -> close();	
	} 
}
